<h1>Template ds_news/index.phtml</h1>

<?php
$news = Mage::registry('news');
foreach ($news as $item) {
echo '<h2>' . $item['title'] . '</h2>';
}
?>

<div class="block">
    <div class="block-title">
        <h2><?php echo $this->__('My block') ?></h2>
        <div class="block-content">
            <form name="input" action="<?php echo $this->getUrl('news/index/add2base') ?>" method="post">
                <label for=""><?php echo $this->__('Enter your any data if you have one.') ?></label>
                <div>
                    <input  class="input-text" type="text" name="myblock2">
                </div>
                <div class="buttons-set">
                <input class="button" type="submit" value="<?php echo $this->__('Apply Data') ?>">
                </div>
            </form>
        </div>
    </div>
</div>