<form name="my-form" action="" method="post">
    <div class="discount">
        <h2><?php echo $this->__('My block') ?></h2>
        <div class="discount-form">
            <label for="myblock"><?php echo $this->__('Enter your any data if you have one.') ?></label>
            <div class="input-box">
                <input class="input-text" type="text" name="myblock">
                <div class="buttons-set">
                    <button type="button"
                            class="button"
                            value="<?php echo $this->__('Apply Data') ?>">
                        <span><span><?php echo $this->__('Apply Data') ?></span></span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>