<form name="my-form" action="" method="post">
    <div class="discount">
        <h2><?php echo $this->__('My block') ?></h2>
        <label for="myblock"><?php echo $this->__('Enter your any data if you have one.') ?></label>

        <div class="input-box">
            <input class="input-text" type="text" name="myinput">
        </div>
        <div class="buttons-set">
            <input type="submit" value="<?php echo $this->__('Apply Data') ?>">
        </div>
    </div>
</form>